feat: Assignment 9 Debugging Basics Initial Commit
Subhasri-V-P/CSharp pull request #10
Opened 2023-09-11 10:36 UTC by Subhasri-V-P

**Background:**
To explore debugging basics

**Implementation:**
1. Debugging tools were explored and its functionalities are documented.
2. Exceptions are handled using Exception settings and breakpoints.
3. A simple application with `OutOfRangeException` is created and it is resolved.

2023-09-25 15:47 UTC, Shaalini-Subrammanian requested changes

2023-09-25 15:47 UTC, Shaalini-Subrammanian commented on README.md
> +  - Now the compiler throws the same exception.
Now the compiler throws the same exception in case of 101 elements

2023-09-26 03:39 UTC, Subhasri-V-P commented on README.md
> +  - Now the compiler throws the same exception.
Statement in the readme.md updated

2023-09-27 11:05 UTC, Shaalini-Subrammanian approved these changes

2023-09-27 15:05 UTC, merged