feat: Assignment 10 Error Handling Initial Commit
Subhasri-V-P/CSharp pull request #11
Opened 2023-09-13 06:58 UTC by Subhasri-V-P

**Background:**
To understand Exception Handling and handle expected and unexpected errors.

**Implementation:**
1. Implemented try/catch/finally block to handle `DivisionByZeroException`.
2. Implemented try/catch/finally block to handle `OutOfRangeException` and a custom message exception is thrown.
3. Custom `InvalidUserInputException` class is created and invalid input for array elements are handled by throwing `InvalidUserInputException` custom exception.
4. Globally handled unexpected exceptions using `UnhandledExceptionEventHandler` and **HandleUnexpectedExceptions()** function.
5. Concepts of stack trace are explored and the printed stack trace is understood.

2023-09-25 16:28 UTC, Shaalini-Subrammanian requested changes

2023-09-25 16:28 UTC, Shaalini-Subrammanian commented on src/ErrorHandling/Program.cs
> +                try
Why do we have so much try..catch blocks?, Try catch has been already implemented for this method at the top level i.e at the method call, so we can remove this inside the method.

Always the try catch should be handled at the top level for example before the method calls.

2023-09-26 03:45 UTC, Subhasri-V-P commented on src/ErrorHandling/Program.cs
> +            int intInput;
Changes as parsedInput

2023-09-26 03:47 UTC, Subhasri-V-P commented on src/ErrorHandling/Program.cs
> +            unparsedInput1 = Console.ReadLine();
refactored code for clean execution

2023-09-26 04:06 UTC, Subhasri-V-P commented on src/ErrorHandling/Program.cs
> +                try
The assignment says we have to handle the exception and throw a new exception with custom message. So I guess this is what is expected to be done.

2023-09-27 11:06 UTC, Shaalini-Subrammanian commented on src/ErrorHandling/Program.cs
> +                try
But it's not a best practice to have try catch everywhere, We should have the try catch at the top level

2023-09-27 15:35 UTC, Subhasri-V-P commented on src/ErrorHandling/Program.cs
> +                try
The exceptions were handled at top level

2023-10-02 13:46 UTC, Shaalini-Subrammanian approved these changes

2023-10-03 03:52 UTC, merged