Feat assignment12 task
Subhasri-V-P/CSharp pull request #13
Opened 2023-09-25 15:20 UTC by Subhasri-V-P

Background:
To work with generics and collections.

Implementation:
Task 1: Working with Lists
Task 2: Using Stacks
Task 3: Working with Queues
Task 4: Understanding Dictionaries

2023-10-02 14:36 UTC, Shaalini-Subrammanian requested changes

2023-10-02 14:36 UTC, Shaalini-Subrammanian commented on src/CollectionsAndGenerics/Program.cs
> +                int userChoice = ValidateInput.Program.GetValidUserChoice(Enum.GetNames(typeof(CollectionsAvailable)).Length);
Can we use extension method instead of just having the GetValidUserChoice as static?

```suggestion
               Enum.GetNames(typeof(CollectionsAvailable)).Length.GetValidUserChoice();
```

I have renamed the Program.cs as `ValidateUserInput` to avoid confusions for this comment screenshot below
![image](https://github.com/Subhasri-V-P/CSharp/assets/97607877/99863887-495c-4aee-9f5a-a2eda2b0da65)

![image](https://github.com/Subhasri-V-P/CSharp/assets/97607877/4591e25d-63a0-47dc-8f6d-789bcf3bfdd0)

These are the changes you have to do for the rest of the methods as well, 

I also wanted you to explore on extension methods

2023-10-02 14:36 UTC, Shaalini-Subrammanian commented on src/CollectionsAndGenerics/Program.cs
> +                        ListHandler<string> listHandlerObject = new ListHandler<string>();
Can we simplify this as 
```suggestion
                        ListHandler<string> listHandlerObject = new ();
```

Same applies for rest of the declarations as well

2023-10-02 14:36 UTC, Shaalini-Subrammanian commented on src/CollectionsAndGenerics/QueueOperations.cs
> +                foreach (OperationsByQueue operations in Enum.GetValues(typeof(OperationsByQueue)))
Can we have a generic method for printing enums?

2023-10-02 14:36 UTC, Shaalini-Subrammanian commented on src/CollectionsAndGenerics/QueueOperations.cs
> +            return this.Persons.Count == 0 ? true : false;
```suggestion
            return this.Persons.Any() ? false : true;
```

2023-10-02 14:36 UTC, Shaalini-Subrammanian commented on src/CollectionsAndGenerics/DictionaryOperations.cs
> +            return this.GradeOfStudents.Count == 0 ? true : false;
```suggestion
            return this.GradeOfStudents.Any() ? false : true;
```

Applies to similar scenarios

2023-10-02 14:37 UTC, Shaalini-Subrammanian commented
![image](https://github.com/Subhasri-V-P/CSharp/assets/97607877/02fcf648-85a3-4d8d-9de0-f19c332fa80c)

Can you check this?

2023-10-03 03:58 UTC, Subhasri-V-P commented on src/CollectionsAndGenerics/Program.cs
> +                    Console.WriteLine($"{(int)collections}. {collections.ToString()}");
Removed ToString() method.

2023-10-03 04:05 UTC, Subhasri-V-P commented on src/ValidateInput/Program.cs
> +        /// <param name="numberOfChoices">number of choices to validate based on enum length</param>
Program class refactored.

2023-10-03 04:05 UTC, Subhasri-V-P commented on src/CollectionsAndGenerics/Program.cs
> +    public partial class Program
Program class refactored.

2023-10-03 04:14 UTC, Subhasri-V-P commented
> ![image](https://user-images.githubusercontent.com/97607877/272001030-02fcf648-85a3-4d8d-9de0-f19c332fa80c.png)
> 
> Can you check this?

I guess you should add dependencies once you pull it from git

2023-10-03 04:25 UTC, Subhasri-V-P commented on src/CollectionsAndGenerics/Program.cs
> +                int userChoice = ValidateInput.Program.GetValidUserChoice(Enum.GetNames(typeof(CollectionsAvailable)).Length);
Changes made in ValidateInput project

2023-10-03 04:31 UTC, Subhasri-V-P commented on src/CollectionsAndGenerics/Program.cs
> +                        ListHandler<string> listHandlerObject = new ListHandler<string>();
Simplified object creation

2023-10-03 05:04 UTC, Subhasri-V-P commented on src/CollectionsAndGenerics/QueueOperations.cs
> +                foreach (OperationsByQueue operations in Enum.GetValues(typeof(OperationsByQueue)))
Function for displaying enum is incuded

2023-10-03 05:09 UTC, Subhasri-V-P commented on src/CollectionsAndGenerics/QueueOperations.cs
> +            return this.Persons.Count == 0 ? true : false;
Changed all IsEmpty() function

2023-10-03 05:10 UTC, Subhasri-V-P commented on src/CollectionsAndGenerics/DictionaryOperations.cs
> +            return this.GradeOfStudents.Count == 0 ? true : false;
Modified all IsEmpty() function

2023-10-04 11:27 UTC, Shaalini-Subrammanian commented
> > ![image](https://user-images.githubusercontent.com/97607877/272001030-02fcf648-85a3-4d8d-9de0-f19c332fa80c.png)
> > Can you check this?
> 
> I guess you should add dependencies once you pull it from git

Why the dependencies are not added to git?

2023-10-04 11:42 UTC, Shaalini-Subrammanian commented on src/CollectionsAndGenerics/Program.cs
> +                int userChoice = ValidateInput.Program.GetValidUserChoice(Enum.GetNames(typeof(CollectionsAvailable)).Length);
> Can we use extension method instead of just having the GetValidUserChoice as static?
> 
> I have renamed the Program.cs as `ValidateUserInput` to avoid confusions for this comment screenshot below ![image](https://user-images.githubusercontent.com/97607877/271993480-99863887-495c-4aee-9f5a-a2eda2b0da65.png)
> 
> ![image](https://user-images.githubusercontent.com/97607877/271993691-4591e25d-63a0-47dc-8f6d-789bcf3bfdd0.png)
> 
> These are the changes you have to do for the rest of the methods as well,
> 
> I also wanted you to explore on extension methods

I still could see Program class have not been renamed
![image](https://github.com/Subhasri-V-P/CSharp/assets/97607877/e2552444-cae2-4094-91eb-6bcfc6f4f1e6)

2023-10-04 13:21 UTC, Subhasri-V-P commented on src/CollectionsAndGenerics/Program.cs
> +                int userChoice = ValidateInput.Program.GetValidUserChoice(Enum.GetNames(typeof(CollectionsAvailable)).Length);
I thought, it was mentioned that this class's name was changed to avoid confusion for me to understand where I should change the methods to extension methods.

2023-10-04 13:21 UTC, Subhasri-V-P commented on src/CollectionsAndGenerics/Program.cs
> +                int userChoice = ValidateInput.Program.GetValidUserChoice(Enum.GetNames(typeof(CollectionsAvailable)).Length);
I have refactored and updated now

2023-10-15 13:16 UTC, Shaalini-Subrammanian approved these changes

2023-10-15 13:16 UTC, Shaalini-Subrammanian commented on src/CollectionsAndGenerics/CollectionManager.cs
> +                    case (int)CollectionsAvailable.Exit:
default case missing

2023-10-16 05:56 UTC, Subhasri-V-P commented on src/CollectionsAndGenerics/CollectionManager.cs
> +                    case (int)CollectionsAvailable.Exit:
Default case added

2023-10-16 06:41 UTC, merged