feat: Assignment 14 Asynchronous Programming Initial Commit
Subhasri-V-P/CSharp pull request #15
Opened 2023-09-30 05:05 UTC by Subhasri-V-P

**Background:**
To understand Asynchronous Programming using async and await.

**Implementation:**
Understanding and Implementing 
1. Async/Await
2. Task Parallel Library
3. Multi-Threading
4. Multi-Layered Async/Await Operations
5. Deadlock Conditions
6. ConfigureAwait
7. Async Void and Async Task with Exceptions

2023-10-12 04:21 UTC, Shaalini-Subrammanian requested changes

2023-10-13 05:31 UTC, Subhasri-V-P commented on src/AsynchronousProgramming/AsyncAndAwait/Program.cs
> +    public class Program
Program class name refactored.

2023-10-13 05:38 UTC, Subhasri-V-P commented on src/AsynchronousProgramming/TaskParallelLibraryImplementation/Program.cs
> +            var randomNumber = new Random();
Main function is refactored and updated.

2023-10-13 05:41 UTC, Subhasri-V-P commented on src/AsynchronousProgramming/MultiThreading/Program.cs
> +            threadOne.Join();
Suggested change was changed.

2023-10-13 05:41 UTC, Subhasri-V-P commented on src/AsynchronousProgramming/DebuggingDeadLock/Program.cs
> +            await programObject.DeadlockMethod();
Added at the end.

2023-10-13 05:42 UTC, Subhasri-V-P commented on src/AsynchronousProgramming/DebuggingDeadLock/Program.cs
> +        /// <returns>Task object to stop execution until completion.</returns>
Documentation updated.

2023-10-15 13:23 UTC, Shaalini-Subrammanian approved these changes

2023-10-16 07:26 UTC, merged