feat: Assignment15 Design pattern IDisposable interface
Subhasri-V-P/CSharp pull request #16
Opened 2023-10-04 10:48 UTC by Subhasri-V-P

**Background: **
Understanding IDisposable interface and managing resources.

**Implementation: **
1. Classes ManagedResource and UnmanagedResource are developed with specific functionality to manage resources.
1. The difference between Managed and Unmanaged Resource are understood.
2. Implemented the IDisposable interface.
3. The Dispose Pattern was implemented.
4. Finalizers were implemented.

2023-10-18 07:53 UTC, Shaalini-Subrammanian requested changes

2023-10-18 12:41 UTC, Subhasri-V-P commented on src/DisposePattern/ResourceManager.cs
> +            managed.Dispose();
Waiting for finalizer to manage unmanaged resources is a non-deterministic task. Finalizers gets executed only when the garbage collector decides to do so. Managing unmanaged resources at right time whenever a developer knows that the object is unused is the best practice to follow.

2023-10-18 12:46 UTC, Subhasri-V-P commented on src/DisposePattern/UnmanagedResource.cs
> +        public StreamWriter StreamWriterObject { get; set; }
Refactored variable names.

2023-10-19 05:07 UTC, Shaalini-Subrammanian approved these changes

2023-10-19 06:12 UTC, merged