feat: Assignment 18 String Manipulation and Regular Expression
Subhasri-V-P/CSharp pull request #20
Opened 2023-10-10 09:17 UTC by Subhasri-V-P

**Background: **
To understand concepts of string manipulation and regular expression.

**Implementation: **
1. A Text Processor System is implemented.
2. This takes 4 directories with 10 files in each directory.
3. The file of user choice is:
        1. Formatted
        2. Analyzed
        3. Extracted for tags, titles and URLs.
        4. Compared with other blog posts.
        5. Searched for a query
4. Difference of StringBuilder and String is understood.
5. Various functionalities of strings and regular expressions are explored.

2023-10-22 15:36 UTC, Shaalini-Subrammanian requested changes

2023-10-22 15:36 UTC, Shaalini-Subrammanian commented on src/TextProcessorSystem/TaskManager.cs
> +            PerformAllTasks(post, directory);
For option 4 why do we get like this 
![image](https://github.com/Subhasri-V-P/CSharp/assets/97607877/a7a1c65b-fc4a-4711-a583-9fe4cf480cdd)

2023-10-22 15:36 UTC, Shaalini-Subrammanian commented on tests/unit/TextProcessorSystem/TextProcessorSystemTests/TextAnalyzerTests.cs
> +            Dictionary<string, int> expectedFrequencyDictionary = new();
```suggestion
            Dictionary<string, int> expectedFrequencyDictionary = new()
                                                       {
                                                           { "This", 2 },
                                                           { "", 2},
                                                       };
```

Instead of adding we can have like this

2023-10-24 10:07 UTC, Subhasri-V-P commented on src/TextProcessorSystem/TaskManager.cs
> +            PerformAllTasks(post, directory);
Values and frequencies are trimmed.

2023-10-24 10:10 UTC, Subhasri-V-P commented on tests/unit/TextProcessorSystem/TextProcessorSystemTests/TextAnalyzerTests.cs
> +            Dictionary<string, int> expectedFrequencyDictionary = new();
Modified way of inserting in dictionary.

2023-11-07 08:39 UTC, Shaalini-Subrammanian approved these changes

2023-11-08 12:27 UTC, merged