feat: Assignment 19 Advanced LINQ
Subhasri-V-P/CSharp pull request #21
Opened 2023-10-13 05:12 UTC by Subhasri-V-P

**Background: ** 
To understand and explore advanced LINQ topics.

**Implementation: ** 
Assignment application covers:
1. Basic and complex LINQ queries.
2. Application of LINQ to objects.
3. Performance implications of LINQ queries.
4. Application of advanced features of LINQ and Expression tree.

2023-11-10 16:05 UTC, Shaalini-Subrammanian requested changes

2023-11-10 16:05 UTC, Shaalini-Subrammanian commented on src/AdvancedLINQ/LINQTaskPerformer.cs
> +                    case (int)TasksToPerform.PerformanceConsiderations:
Task 4: LINQ to SQL / Entity Framework , why this is not executed

2023-11-11 01:55 UTC, Subhasri-V-P commented on src/AdvancedLINQ/LINQTaskPerformer.cs
> +                    case (int)TasksToPerform.PerformanceConsiderations:
It was removed from assignment question.

2023-11-11 05:12 UTC, Shaalini-Subrammanian approved these changes

2023-11-11 06:18 UTC, merged