feat: Assignment 20 Reflections in C#
Subhasri-V-P/CSharp pull request #22
Opened 2023-10-15 11:59 UTC by Subhasri-V-P

**Background: **
To understand and create dynamic libraries using reflection.

**Implementation: **
Application performs:
1. Inspecting Assembly Metadata
2. Dynamic Object Inspection
3. Dynamic Method Invoking
4. Dynamic Type Building
5. Plugin System interface loading and method invoking
6. Mocking Framework

2023-11-04 16:23 UTC, Shaalini-Subrammanian requested changes

2023-11-04 16:23 UTC, Shaalini-Subrammanian commented on src/Reflections/Utility.cs
> +            classToSerialize.StudentObject.StudentName = "TestName";
Any specific reason for this kind of implementation instead of

`ClassToSerialize classToSerialize = new () { StudentObject = new Student() { StudentId = 1, StudentName = "abc" }, Course = "Mathematics" };` ?

2023-11-04 16:23 UTC, Shaalini-Subrammanian commented on src/Reflections/SerializationAPI.cs
> +            foreach (PropertyInfo property in properties)
`Reflection.Emit` I couldn't  find the usage of this here

2023-11-06 03:58 UTC, Subhasri-V-P commented on src/Reflections/AssemblyMetaDataInspector.cs
> +        /// </summary>
The question was modified to use the same assembly. Thus, executing assembly is got.

2023-11-06 04:10 UTC, Subhasri-V-P commented on src/Reflections/AssemblyMetaDataInspector.cs
> +            MethodInfo[] methodsInAssembly;
Added Console colors.

2023-11-06 04:15 UTC, Subhasri-V-P commented on src/Reflections/Utility.cs
> +            classToSerialize.StudentObject.StudentName = "TestName";
updated coding style.

2023-11-06 04:23 UTC, Subhasri-V-P commented on src/Reflections/SerializationAPI.cs
> +            foreach (PropertyInfo property in properties)
In task 7, Point number 3,4,5 was removed.

2023-11-07 08:42 UTC, Shaalini-Subrammanian approved these changes

2023-11-11 06:43 UTC, merged