feat: Contact Manager App Initial Commit
Subhasri-V-P/CSharp pull request #3
Opened 2023-08-18 13:28 UTC by Subhasri-V-P

2023-08-20 13:09 UTC, Shaalini-Subrammanian requested changes

2023-08-20 13:09 UTC, Shaalini-Subrammanian commented on src/ContactManagerApp/Program.cs
> +                        contactList = contactList[0].Edit(contactList, editId, editField);
We are duplicating

2023-08-20 13:09 UTC, Shaalini-Subrammanian commented on src/ContactManagerApp/Contact.cs
> +        /// <value>String input</value>
I have mentioned in other comments to have a List of contacts in this class.

`private List<Contact> ContactList{get;set;}`


For adding a contact have a method
`public void AddContact(Contact newContactDetails)
{
    ContactList.Add(newContactDetails);
    Console.WriteLine("Contact added successfully");
}`

Follow similar kind of approach for other methods as well

2023-08-20 13:10 UTC, Shaalini-Subrammanian commented
> `_ No description provided. _`


A proper description should be provided for every PR that you raise

2023-08-21 04:18 UTC, Subhasri1005 commented on src/ContactManagerApp/Contact.cs
> +                if (flag == true)
The id of the contact objects after one deletion is fixed such that it is continuous always Eg: if id 1 is deleted the id of the object in 2 is reduced by 1 1--->obj1 2--->obj2 After deletion 1--->obj2

2023-08-21 04:19 UTC, Subhasri1005 commented on src/ContactManagerApp/Contact.cs
> +            foreach (Contact contact in contactList.ToList())
The template doesn't allow direct editing in the list

2023-08-21 07:28 UTC, Subhasri1005 commented on src/ContactManagerApp/Program.cs
> +                        while (string.IsNullOrWhiteSpace(entryToDelete))
It is provided to make sure only null or whitespace should not be given but the fields can have whitespaces

2023-08-22 09:00 UTC, Shaalini-Subrammanian requested changes

2023-08-22 09:00 UTC, Shaalini-Subrammanian commented on src/ContactManagerApp/Program.cs
> +                        Console.WriteLine("\nEditable fields");
Have all the console as single line using \n

2023-08-22 10:47 UTC, Subhasri-V-P commented on src/ContactManagerApp/Contact.cs
> +            foreach (Contact contactItem in contactsFound.Where(contactItem => contactItem.Id == id))
The search result may have more than one object as well. This is because the program returns everything that matches a Incase user searches for a

2023-08-23 05:28 UTC, Shaalini-Subrammanian commented on src/ContactManagerApp/Contact.cs
> +                Console.WriteLine($"\nID: {contact.Id}\nName: {contact.Name}\nPhone Number: {contact.PhoneNumber}\nEmail: {contact.Email}\nNotes: {contact.AdditionalNotes}\n");
Please check the indentation

2023-08-23 05:46 UTC, Subhasri-V-P commented on src/ContactManagerApp/Contact.cs
> +                Console.WriteLine($"\nID: {contact.Id}\nName: {contact.Name}\nPhone Number: {contact.PhoneNumber}\nEmail: {contact.Email}\nNotes: {contact.AdditionalNotes}\n");
Actually, I am not able to understand this comment

2023-08-23 06:48 UTC, Shaalini-Subrammanian requested changes

2023-08-23 06:48 UTC, Shaalini-Subrammanian commented on src/ContactManagerApp/Contact.cs
> +            return contactList.Count == 0 ? true : false;
`contactList.Count.Any() ? true : false;`

This is one another method instead of using Count ( Just added FYI, no need to change, while moving forward we can use Any() instead of Count() )

2023-08-23 06:48 UTC, Shaalini-Subrammanian commented on src/ContactManagerApp/Program.cs
> +                int iterator = 1;
Remove iterator 

Inside forloop use 

`{(int)operation}` -> `Console.WriteLine($"{(int)operations}. {operations} contact data");`

2023-08-23 06:48 UTC, Shaalini-Subrammanian commented on src/ContactManagerApp/Program.cs
> +                                "\n1. Name" +
Can we use `nameof(Contact.Name)` applies for other properties email etc..

It is always good not to hard code the values manually

2023-08-23 06:59 UTC, Shaalini-Subrammanian requested changes

2023-08-23 06:59 UTC, Shaalini-Subrammanian commented on README.md
> +- `List of Contact objects` is declared.
Remove this line, as we are not declaring the list in main

2023-08-23 06:59 UTC, Shaalini-Subrammanian commented on README.md
> +- All the inputs are `validated`.
this can be like `Inputs are validated based on the regex for the particular field`

2023-08-23 06:59 UTC, Shaalini-Subrammanian commented on README.md
> + 1. Gets all the inputs from the user.
It is so blank, What are all the inputs?

2023-08-23 06:59 UTC, Shaalini-Subrammanian commented on README.md
> + 3. User input is requested until the user provides input in proper format.
If the input given is wrong, User input is requested until the user provides input in proper format.

2023-08-23 06:59 UTC, Shaalini-Subrammanian commented on README.md
> + ### STORE
It is not store any more! Add. I guess you have forgot to change the method names in readme file. Please update it

2023-08-23 06:59 UTC, Shaalini-Subrammanian commented on README.md
> + 1. Get some entry form the user.
Get user input to identify the file to edit

2023-08-23 06:59 UTC, Shaalini-Subrammanian commented on README.md
> + 3. If more than one result is displayed.
What happens if only one result is present?, That is not mentioned in this document

2023-08-23 06:59 UTC, Shaalini-Subrammanian commented on README.md
> + 6. Get user input and edit the field using `Edit()` function.
6. Get user input, validate the data to be edit using the respective regex.
7. Edit the field using Edit

2023-08-23 06:59 UTC, Shaalini-Subrammanian commented on README.md
> + 1. Get some entry form the user.
Change the 1st point based on the comment I've added for edit

2023-08-23 06:59 UTC, Shaalini-Subrammanian commented on README.md
> + 1. Get some entry form the user.
SAme applies here

2023-08-23 06:59 UTC, Shaalini-Subrammanian commented on README.md
> +The class includes validation rules in the form of a regular expression (`regex`) for input validation.
Mention what are all the validation parameters with explanations

2023-08-23 06:59 UTC, Shaalini-Subrammanian commented on README.md
> +- `Contact(id, name, email, phoneNumber, notes)`: Initializes a new instance of the `Contact` class with the provided parameters.
One another default constructor is added now. Please include that as well

2023-08-23 06:59 UTC, Shaalini-Subrammanian commented on README.md
> +- `Display(contactList)`: Displays values of the contact objects in the provided list.
Update these methods along with the current name. And now we are not passing the lists as one of the parameters

2023-08-23 11:19 UTC, Subhasri-V-P commented on src/ContactManagerApp/.editorconfig
> +SA1629
.editorconfig is added to .gitignore file

2023-08-23 11:20 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +        private enum Tasks
Tasks is renamed to OperationsToPerform

2023-08-23 11:20 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +            Store = 1,
Store enum is renamed to be Add

2023-08-23 11:20 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +                Console.WriteLine($"1. {Tasks.Store} contact data");
The requested code snippet is included knowing its functionality

2023-08-23 11:21 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +                unparsedInput1 = Console.ReadLine();
Renamed variables appropriately

2023-08-23 11:21 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +                while (!int.TryParse(unparsedInput1, out taskToPerform) || !Enum.IsDefined(typeof(Tasks), taskToPerform))
Variable is renamed

2023-08-23 11:22 UTC, Subhasri-V-P commented on src/ContactManagerApp/Contact.cs
> +                Console.WriteLine();
\n is used and more function calls are avoided

2023-08-23 11:22 UTC, Subhasri-V-P commented on src/ContactManagerApp/Contact.cs
> +            Console.WriteLine("Deleted!!!");
\n is replaced with many Writeline calls

2023-08-23 11:23 UTC, Subhasri-V-P commented on src/ContactManagerApp/Contact.cs
> +        public List<Contact> Edit(List<Contact> contactList, int entryId, int fieldToEdit)
`contactList` is created in the Contact class

2023-08-23 11:24 UTC, Subhasri-V-P commented on src/ContactManagerApp/Contact.cs
> +                while (string.IsNullOrWhiteSpace(name) || !Regex.IsMatch(name, nameRegex))
Common method to check validation is added `validateUserInput()`

2023-08-23 11:25 UTC, Subhasri-V-P commented on src/ContactManagerApp/Contact.cs
> +                while (string.IsNullOrWhiteSpace(contactNumber) || !Regex.IsMatch(contactNumber, contactNumberRegex))
Function is updated similarly

2023-08-23 11:25 UTC, Subhasri-V-P commented on src/ContactManagerApp/Contact.cs
> +        public bool CheckId(List<Contact> contact, int id)
Linq statement is used

2023-08-23 11:26 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +                        Console.WriteLine();
\n is used instead of Console.WriteLine()

2023-08-23 11:27 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +                        while (string.IsNullOrWhiteSpace(name) || !Regex.IsMatch(name, nameRegex))
Function call is made and while loop is removed

2023-08-23 11:27 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +
Comment updated to Added contact successfully

2023-08-23 11:28 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +            List<Contact> contactList = new List<Contact>();
AddContactData() function is added

2023-08-23 11:29 UTC, Subhasri-V-P commented on src/ContactManagerApp/Contact.cs
> +        public void View(List<Contact> contactList)
Function names updated

2023-08-23 11:29 UTC, Subhasri-V-P commented on src/ContactManagerApp/Contact.cs
> +            List<Contact> contacts = new List<Contact>();
variable name updated

2023-08-23 11:29 UTC, Subhasri-V-P commented on src/ContactManagerApp/Contact.cs
> +            if (flag == true)
flag field is removed

2023-08-23 11:30 UTC, Subhasri-V-P commented on src/ContactManagerApp/Contact.cs
> +        public List<Contact> Delete(List<Contact> contactList, int entryId)
Function is renamed

2023-08-23 11:32 UTC, Subhasri-V-P commented on src/ContactManagerApp/Contact.cs
> +        public List<Contact> Edit(List<Contact> contactList, int entryId, int fieldToEdit)
Methods functionality is updated and inputs are got from Main() function and passed as parameters

2023-08-23 11:32 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +                        contactList = contactList[0].Edit(contactList, editId, editField);
No duplication is done

2023-08-23 11:33 UTC, Subhasri-V-P commented on src/ContactManagerApp/Contact.cs
> +            if (contactList.Count == 0)
Ternary operators used

2023-08-23 11:34 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +                        Console.WriteLine("\nEditable fields");
All consoles writelines are made in single line

2023-08-23 11:34 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +                        contacts = contactList[0].Search(searchId, contactList);
Returns are not done to remove duplication

2023-08-23 11:35 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +                        List<Contact> contactsFound = new List<Contact>();
contactsFound is declared in Contact class

2023-08-23 11:36 UTC, Subhasri-V-P commented on src/ContactManagerApp/Contact.cs
> +                Console.WriteLine($"\nID: {contact.Id}\nName: {contact.Name}\nPhone Number: {contact.PhoneNumber}\nEmail: {contact.Email}\nNotes: {contact.AdditionalNotes}\n");
Indentations corrected

2023-08-23 11:36 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +                int iterator = 1;
Iterator removed

2023-08-23 11:36 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +                                "\n1. Name" +
nameof() function is used

2023-08-23 11:37 UTC, Subhasri-V-P commented on README.md
> +- `List of Contact objects` is declared.
Line removed

2023-08-23 11:37 UTC, Subhasri-V-P commented on README.md
> +- All the inputs are `validated`.
Text updated

2023-08-23 11:37 UTC, Subhasri-V-P commented on README.md
> + 1. Gets all the inputs from the user.
Inputs specified

2023-08-23 11:38 UTC, Subhasri-V-P commented on README.md
> + 3. User input is requested until the user provides input in proper format.
Validation documentation is done

2023-08-23 11:38 UTC, Subhasri-V-P commented on README.md
> + ### STORE
Store is changed to add

2023-08-23 11:39 UTC, Subhasri-V-P commented on README.md
> + 1. Get some entry form the user.
Text updated

2023-08-23 11:40 UTC, Subhasri-V-P commented on README.md
> + 3. If more than one result is displayed.
Corrections updated

2023-08-23 11:40 UTC, Subhasri-V-P commented on README.md
> + 6. Get user input and edit the field using `Edit()` function.
Appropriate documentation texts added

2023-08-23 11:42 UTC, Subhasri-V-P commented on README.md
> + 1. Get some entry form the user.
Texts updated

2023-08-23 11:43 UTC, Subhasri-V-P commented on README.md
> + 1. Get some entry form the user.
Text documentation updated

2023-08-23 11:44 UTC, Subhasri-V-P commented on README.md
> +The class includes validation rules in the form of a regular expression (`regex`) for input validation.
Validation parameters are included with explanations

2023-08-23 11:47 UTC, Subhasri-V-P commented on README.md
> +- `Display(contactList)`: Displays values of the contact objects in the provided list.
Method names and its functionality details are updated in the documentation

2023-08-23 11:47 UTC, Subhasri-V-P commented on src/ContactManagerApp/Program.cs
> +                        while (!int.TryParse(unparsedFieldToChange, out editField) || (editField != 1 && editField != 2 && editField != 3 && editField != 4))
Changes made to optimize conditions

2023-08-23 13:45 UTC, Shaalini-Subrammanian approved these changes

2023-08-23 13:48 UTC, merged