Feat assignment3 task
Subhasri-V-P/CSharp pull request #4
Opened 2023-08-22 10:20 UTC by Subhasri-V-P

ASSIGNMENT 3

Visual Studio 2022 community version has been downloaded and required packages along with CStarterTemplate has been installed.

TASK1
A C# project is created using `Ctrl+Shift+N`. Specific name and location of the project is chosen. Click "Create" or "OK" to create the project.
Project Structure and Visual Studio Interface is explored

TASK 2
Writing and Running a Simple C# Console App in Visual Studio
Open `Program.cs` file in Visual Studio, write some simple C# code in the `Main()` method, build and run the application, and observe the output. 
Project is built and output is observed.

TASK 3
Adding References and NuGet Packages in Visual Studio. Newtonsoft.json package is used to deserialize json file.

TASK 4 
Debugging and Breakpoints in Visual Studio
Breakpoints are set and debugging features and tools are explored

TASK 5
Additional Visual Studio Features are explored and code refactoring options are discovered.

2023-08-23 11:25 UTC, Shaalini-Subrammanian requested changes

2023-08-23 11:25 UTC, Shaalini-Subrammanian commented on src/IntroductionToVisualStudio/Program.cs
> +            var jsonFile = File.ReadAllText(@"D:\CSharp\src\IntroductionToVisualStudio\JsonFile.json");
One suggestion, We can use `Directory.GetCurrentDirectory()` to get the current directory, using this we can append our Json file name at last.

Even though this PR is not a part of your assignment, I wish you could explore on it as this may help you in the future

2023-08-23 11:25 UTC, Shaalini-Subrammanian commented on src/IntroductionToVisualStudio/Student.cs
> +            Console.WriteLine($"Id of the student: {this.Id}");
I guess this keyword is not necessary here, Even without this we can print the Id, Name and Description. Can you check on it

2023-08-23 13:15 UTC, Subhasri-V-P commented on src/IntroductionToVisualStudio/Program.cs
> +            var jsonFile = File.ReadAllText(@"D:\CSharp\src\IntroductionToVisualStudio\JsonFile.json");
I have created jsonFile in solution folder. The current directory returns D:\CSharp\src\IntroductionToVisualStudio\bin\Debug\net6.0 then how can I append?

2023-08-23 13:42 UTC, Shaalini-Subrammanian commented on src/IntroductionToVisualStudio/Program.cs
> +            var jsonFile = File.ReadAllText(@"D:\CSharp\src\IntroductionToVisualStudio\JsonFile.json");
`Directory.GetCurrentDirectory()` gives you the D:\CSharp\src\IntroductionToVisualStudio, you can use like
`string.concat(Directory.GetCurrentDirectory(),bin\Debug\net6.0)`  or please explore on `Path.GetDirectoryName(Application.ExecutablePath)` also

2023-08-24 05:43 UTC, Subhasri-V-P commented on src/IntroductionToVisualStudio/Program.cs
> +            var jsonFile = File.ReadAllText(@"D:\CSharp\src\IntroductionToVisualStudio\JsonFile.json");
The expected function is used.

2023-08-24 05:56 UTC, Shaalini-Subrammanian commented on src/IntroductionToVisualStudio/Program.cs
> +            // var jsonFile = File.ReadAllText(@"D:\CSharp\src\IntroductionToVisualStudio\JsonFile.json");
Remove this comment

2023-08-24 05:57 UTC, Shaalini-Subrammanian commented
Approved with suggestions

2023-08-24 05:57 UTC, Subhasri-V-P commented on src/IntroductionToVisualStudio/Program.cs
> +            // var jsonFile = File.ReadAllText(@"D:\CSharp\src\IntroductionToVisualStudio\JsonFile.json");
Removed comment

2023-08-24 05:58 UTC, Shaalini-Subrammanian approved these changes

2023-08-24 06:34 UTC, merged