feat: Assignment 4 Initial Commit
Subhasri-V-P/CSharp pull request #5
Opened 2023-08-28 07:31 UTC by Subhasri-V-P

Background:
To explore on dependencies and to solve circular dependency.

Implementation:
**Dependency Order**
Assignment4_GreetingsApp -> Assignment4_MathApp -> Assignment4_DisplayApp -> Assignment4_ProjectE and  Assignment4_UtilityApp

- Assignment4_GreetingsApp - Prints greeting message and calls Assignment4_MathApp's functionalities
- Assignment4_MathApp - Performs mathematical operations of user's choice and calls Assignment4_DisplayApp
- Assignment4_DisplayApp - Prints the results of the operation and has validate function
                                           - This validate function would create circular dependency as it access the functions of Assignment4_MathApp
                                           - To remove this dependency the common function is added to Assignment4_ProjectE
                                           - And Assignment4_ProjectE is added as dependency for Assignment4_DisplayApp
- Assignment4_UtilityApp - It is added as a dependency for Assignment4_DisplayApp. Displays Thank you message. Called from Assignment4_MathApp.
- Assignment4_ProjectE - It is added as a dependency for Assignment4_DisplayApp. Has input validation function which uses input got from user from Assignment4_MathApp Project.

2023-08-28 13:22 UTC, Shaalini-Subrammanian requested changes

2023-08-28 13:22 UTC, Shaalini-Subrammanian commented on src/Assignment4_MathApp/Program.cs
> +                Console.WriteLine($"1. {MathematicalOperations.Addition}");
We can use foreach loop as did in last assignment

2023-08-28 13:22 UTC, Shaalini-Subrammanian commented on src/Assignment4_MathApp/MathematicalCalculations.cs
> +        public float Mul(float x, float y)
Proper naming practices should be followed

2023-08-28 13:28 UTC, Subhasri-V-P commented on src/Assignment4_MathApp/Program.cs
> +        public static void Main(string[] args)
It is mandatory to have main functions in all newly created projects in CSharp_Starter_Template. I tried removing it but build would fail if I do so

2023-08-28 13:28 UTC, Subhasri-V-P commented on src/Assignment4_DisplayApp/Program.cs
> +        public static void Main(string[] args)
Warnings will rise

2023-08-28 13:40 UTC, Subhasri-V-P commented on src/Assignment4_MathApp/Program.cs
> +                Console.WriteLine($"1. {MathematicalOperations.Addition}");
Loop is used

2023-08-28 13:41 UTC, Subhasri-V-P commented on src/Assignment4_MathApp/MathematicalCalculations.cs
> +        public float Mul(float x, float y)
Proper naming conventions are employed

2023-08-30 04:39 UTC, Shaalini-Subrammanian requested changes

2023-08-30 04:39 UTC, Shaalini-Subrammanian commented on README.md
> +`Assignment4_MathApp` is added as a dependency for this project.
This can be detailly mentioned as, for which project this is in dependency with. Eg: GreetingsApp has the dependency of MathApp / GreetingsApp depends on MathApp. 

Applies for all

2023-08-30 04:39 UTC, Shaalini-Subrammanian commented on src/Assignment4_DisplayApp/Program.cs
> +            Console.WriteLine($"Integer 1: {input1}");
This isn't Integer 1 it should be Input 1

2023-08-30 04:39 UTC, Shaalini-Subrammanian commented on src/Assignment4_MathApp/MathematicalCalculations.cs
> +    using Assignment4_UtilityApp;
Assignment4_UtilityApp namespace is not used in this class, we can remove it.

This applies for all classes, remove the unused namespaces

2023-08-30 04:39 UTC, Shaalini-Subrammanian commented on src/Assignment4_MathApp/Program.cs
> +                    Console.WriteLine($"{(int)mathematicalOperations}. {mathematicalOperations.ToString()}");
ToString() can be removed

2023-08-30 04:39 UTC, Shaalini-Subrammanian commented on src/Assignment4_MathApp/Program.cs
> +        public static void ProgramClassMainFunction()
The name of the method is not meaningful. I didn't understand the purpose of the method until I go through the code.

The name can be GetUserInputs, Since you are getting the input and performing it name the method accordingly.

The method name should not include and/or as per clean code practices. A method should be capable of doing only one action per time

2023-08-30 04:41 UTC, Shaalini-Subrammanian commented
![Project Misplaced](https://github.com/Subhasri-V-P/CSharp/assets/97607877/ac591164-db29-49da-b75b-11cc854c88b5)

Why this project alone is placed outside of src folder?

2023-08-30 07:47 UTC, Subhasri-V-P commented on README.md
> +`Assignment4_MathApp` is added as a dependency for this project.
Dependency text added.

2023-08-30 07:49 UTC, Subhasri-V-P commented on src/Assignment4_DisplayApp/Program.cs
> +            Console.WriteLine($"Integer 1: {input1}");
Printing statement updated

2023-08-30 07:50 UTC, Subhasri-V-P commented on src/Assignment4_MathApp/MathematicalCalculations.cs
> +    using Assignment4_UtilityApp;
The unused Namespaces are removed

2023-08-30 07:51 UTC, Subhasri-V-P commented on src/Assignment4_MathApp/Program.cs
> +                    Console.WriteLine($"{(int)mathematicalOperations}. {mathematicalOperations.ToString()}");
ToString() removed

2023-09-04 04:11 UTC, Shaalini-Subrammanian requested changes

2023-09-04 04:11 UTC, Shaalini-Subrammanian commented on README.md
> +- Calls the `ProgramClassMainFunction` of ProjectB(`Assignment4_MathApp`) to start performing operations.
Update the method name

2023-09-04 04:12 UTC, Shaalini-Subrammanian approved these changes

2023-09-04 04:12 UTC, Shaalini-Subrammanian commented
Approved with suggestions

2023-09-04 04:38 UTC, Subhasri-V-P commented on README.md
> +- Calls the `ProgramClassMainFunction` of ProjectB(`Assignment4_MathApp`) to start performing operations.
Summary is updated

2023-09-04 04:49 UTC, merged