feat: Assignment 6 initial commit
Subhasri-V-P/CSharp pull request #7
Opened 2023-08-30 07:30 UTC by Subhasri-V-P

**Background:**
To explore object oriented concepts using C Sharp

**Implementation:**
- The classes are created according to the inheritance order provided.
- Abstract methods are declared in parent class
- They were overridden and used in child classes
- The functionality benefits of OOPS are tried and explored
- The application works asking user inputs for type of object to create, the properties of the classes.
- The user inputs are validated appropriately
- The details collected and calculated using objects are printed using functions

2023-09-05 13:40 UTC, Shaalini-Subrammanian requested changes

2023-09-05 13:40 UTC, Shaalini-Subrammanian commented on src/Assignment6_ShapeHeirarchy/Program.cs
> +
`Shape shapeOfAnObject = default;`

use this instance for creating the object

Eg: `shapeOfAnObject = new Rectangle(rectangleColorInput, length, breadth);`

Call the display method after the switch, in this way, we can have method invoking as generic

2023-09-05 13:40 UTC, Shaalini-Subrammanian commented on src/Assignment6_ShapeHeirarchy/Program.cs
> +                        Console.WriteLine("Enter color of the shape: ");
since getting color is common for all shapes, can we have this before the switch case?

2023-09-05 13:40 UTC, Shaalini-Subrammanian commented on src/Assignment6_ShapeHeirarchy/Program.cs
> +                        while (string.IsNullOrEmpty(rectangleColorInput))
What if the input contains symbols?

2023-09-05 13:40 UTC, Shaalini-Subrammanian commented on src/Assignment6_ShapeHeirarchy/Program.cs
> +                Console.WriteLine("Enter valid input and Adhere to the options(1/2):");
`options(1/2/3)` applies for other projects as well

2023-09-05 13:40 UTC, Shaalini-Subrammanian commented on src/Assignment6_ShapeHeirarchy/Program.cs
> +        public static int GetValidUserChoice()
Since we are using the same method for all projects, can we have a one common place so that we can use these two methods for all the projects.

2023-09-05 13:40 UTC, Shaalini-Subrammanian commented on src/Assignment6_EmployeeHeirarchy/Program.cs
> +                        Console.WriteLine("Enter name of the employee: ");
We can get the employee name before the switch statement?

2023-09-05 13:40 UTC, Shaalini-Subrammanian commented on src/Assignment6_EmployeeHeirarchy/Program.cs
> +                        Employee managerObject = new Manager(nameOfManager, managerSalary);
Please refer the Shapes project comment for creating this object as generic and calling the print details method after switch

2023-09-05 13:40 UTC, Shaalini-Subrammanian commented on src/Assignment6_EmployeeHeirarchy/Program.cs
> +            bool exit = true;
Exit has to be false -> Based on the name you have given, exit means exiting the switch, or change the 
`bool exit = true;
do
{
  switch(cases)
 {
   case (int)exit:
    exit = true;
    break;
}
}while(!exit)`


This applies for other projects as well

2023-09-05 13:40 UTC, Shaalini-Subrammanian commented on src/Assignment6_BankingSystem/Program.cs
> +        public static void Main(string[] args)
Make sure you have made the changes I have requested in other comments in this as well

2023-09-06 04:15 UTC, Subhasri-V-P commented on src/Assignment6_ShapeHeirarchy/Program.cs
> +
Generic declaration is used

2023-09-06 04:15 UTC, Subhasri-V-P commented on src/Assignment6_ShapeHeirarchy/Program.cs
> +                        Console.WriteLine("Enter color of the shape: ");
Common attributes are got before switch

2023-09-06 04:16 UTC, Subhasri-V-P commented on src/Assignment6_ShapeHeirarchy/Program.cs
> +                Console.WriteLine("Enter valid input and Adhere to the options(1/2):");
Printing statement changed

2023-09-06 04:16 UTC, Subhasri-V-P commented on src/Assignment6_EmployeeHeirarchy/Program.cs
> +                        Console.WriteLine("Enter name of the employee: ");
Common attributes are bought before switch

2023-09-06 04:19 UTC, Subhasri-V-P commented on src/Assignment6_EmployeeHeirarchy/Program.cs
> +            bool exit = true;
exit value was changed

2023-09-06 04:19 UTC, Subhasri-V-P commented on src/Assignment6_ShapeHeirarchy/Program.cs
> +                        while (string.IsNullOrEmpty(rectangleColorInput))
Regex added

2023-09-06 04:25 UTC, Subhasri-V-P commented on src/Assignment6_EmployeeHeirarchy/Program.cs
> +                        Employee managerObject = new Manager(nameOfManager, managerSalary);
print details method call updated

2023-09-06 04:34 UTC, Subhasri-V-P commented on src/Assignment6_ShapeHeirarchy/Program.cs
> +        public static int GetValidUserChoice()
New project to validate user input is created and added as dependency to validate user choice

2023-09-06 04:35 UTC, Subhasri-V-P commented on src/Assignment6_BankingSystem/Program.cs
> +        public static void Main(string[] args)
Changes updated in all projects

2023-09-08 04:25 UTC, Shaalini-Subrammanian requested changes

2023-09-08 04:25 UTC, Shaalini-Subrammanian commented on src/Assignment6_ShapeHeirarchy/Program.cs
> +                if (shapeObject != null)
shapeObject?.PrintDetails()

2023-09-08 04:25 UTC, Shaalini-Subrammanian commented on src/Assignment6_BankingSystem/Program.cs
> +        public static float GetValidInput(string printingData)
Can we move this method to ValidateUserChoice

2023-09-08 04:51 UTC, Subhasri-V-P commented on src/Assignment6_ShapeHeirarchy/Program.cs
> +                if (shapeObject != null)
call to printDetails() updated

2023-09-08 04:52 UTC, Subhasri-V-P commented on src/Assignment6_BankingSystem/Program.cs
> +        public static float GetValidInput(string printingData)
GetValidFloatInput() and GetValidIntInput() function moved to ValidateInput Project

2023-09-08 04:54 UTC, Shaalini-Subrammanian approved these changes

2023-09-08 05:23 UTC, merged