feat: Assignment 8 Memory management Initial Commit
Subhasri-V-P/CSharp pull request #9
Opened 2023-09-07 09:29 UTC by Subhasri-V-P

**Background:**
To understand value and reference types, stack and heap, garbage collection and IDisposable Interface.

**Implementation:**
- Task 1
1. An employee and trainee object is created. The properties of those class and structures can be created, modified and displayed. 
2. ModifyId() method is called to understand the difference between value and reference type
- Task 2
1. Calls `CreateLargeArrayOfIntegers` and `CalculationOnLocalVariables` for noticing the changes in memory.
- Task 3
1. Created and deleted a large number of objects, manually influenced garbage collection, and monitored memory usage.
- Task 4
1. The `Program` class creates an instance of `FileWriter` and writes content to a file named "textFile.txt."
2. Then reads and displays the contents of "textFile.txt."

2023-09-11 07:36 UTC, Shaalini-Subrammanian requested changes

2023-09-11 07:36 UTC, Shaalini-Subrammanian commented on src/ValueAndReferenceTypes/Trainee.cs
> +            }
Its Good to have default case
```suggestion
       default:
            break;
            }
```

2023-09-15 06:54 UTC, Shaalini-Subrammanian requested changes

2023-09-15 06:54 UTC, Shaalini-Subrammanian commented on src/GarbageCollection/Program.cs
> +            for (int i = 0; i < 100000; i++)
```suggestion
           while (StudentsList.Count < 100000)
           {
                   StudentsList.Add(new Student() { Id = StudentsList.Count + 1 });
           }
```

2023-09-15 06:54 UTC, Shaalini-Subrammanian commented on src/ValueAndReferenceTypes/Employee.cs
> +        public void DisplayDetails()
Shall we use inheritance and override these methods?

2023-09-15 07:17 UTC, Subhasri-V-P commented on src/ValueAndReferenceTypes/Employee.cs
> +        public void DisplayDetails()
We can use inheritance if both of them were classes But here one is class and the other one is structure

2023-09-15 07:30 UTC, Subhasri-V-P commented on src/GarbageCollection/Program.cs
> +            for (int i = 0; i < 100000; i++)
Loop statement updated

2023-09-15 08:26 UTC, Shaalini-Subrammanian approved these changes

2023-09-15 10:16 UTC, merged